# Generated by Django 4.0 on 2021-12-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
