# Generated by Django 4.0 on 2021-12-14 16:59
import os
from django.db import migrations


def create_admin(apps, schema_editor):
    User = apps.get_model('question', 'User')
    User.objects.create_superuser(username='admin', password=os.environ.get('admin_password', '1'), is_active=True)


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin, lambda x, y: None)
    ]
